### ISSUE TITLE
Recorded_at/Partial Updates

### ISSUE THREAD

**Issue by arettberg** [kylejginavan/youtube_it#134]
When updating a video, the recorded_at field gets cleared, as youtube_it does not yet support this attribute. This problem led me to a broader problem: anytime youtube adds a new feature, youtube_it has to be updated to support it. YouTube now allows partial video updates using a PATCH call instead of a PUT. Sadly I don't possess the techno-wizardry to make this happen myself. Any hope to make this happen in the near future?

https://developers.google.com/youtube/2.0/developers_guide_protocol#Partial_Updates

**Comment by zef** [comment]
Yes, I agree that this is a problem.

As I just referenced in #135 keywords are now being deleted for our users because the incoming array of keywords is blank, even if keywords actually exist in YouTube.

I haven't contributed before but I'm looking into this. Faraday supports PATCH so I'm trying it out now...

**Comment by zef** [comment]
I made a bit of progress in modifying the update method to perform a PATCH and removing some default argument options, but ran into some problems in the end that I can't pursue any longer right now.

I'm not sure if this behavior should be the default or if it should be an explicit opt-in thing.

On one hand, performing a PATCH as the default for update could prevent people from unexpected data loss. On the other hand [Google says](https://developers.google.com/youtube/2.0/developers_guide_protocol_partial_updates) it's an "experimental feature, which means that it might change unexpectedly."

Here's the error I got when I changed update to perform a PATCH instead of PUT:

```
UploadError: Content-Type application/atom+xml;charset=UTF-8 is not a valid input type.: invalidContentType
from [...]/lib/youtube_it/middleware/faraday_youtubeit.rb:27:in `on_complete'
```
