### ISSUE TITLE
Keywords no longer being returned

### ISSUE THREAD

**Issue by mattschultz** [kylejginavan/youtube_it#135]
When querying a video (e.g. client.video_by(link)), it does not return the video's keywords.

**Comment by chebyte** [comment]
check please cause is working fine for me

```
puts client.video_by("https://www.youtube.com/watch?v=QsbmrCtiEUU").title

#fundacion tuquito

```

**Comment by zef** [comment]
I suspect that this is related to these changes announced back in August:

http://apiblog.youtube.com/2012/08/video-tags-just-for-uploaders.html
http://youtubecreator.blogspot.com/2012/08/tags-removed-from-video-watch-pages.html

@chebyte if you haven't seen this yet you might want to prepare for it. This just started happening to us, we're no longer getting keywords back. They could be rolling out this change slowly or something.

I've bitten by this recently on an app for a client. When we are updating video metadata the existing tags are getting cleared since we have to pass all parameters to update the video. We are still allowed to write tags so we are passing back the empty array we got and are overwriting the tags that were there.
