### ISSUE TITLE
video_id is missing

### ISSUE THREAD

**Issue by Elgeor** [kylejginavan/youtube_it#168]
Hi, 

i have a problem. I try to implement example of this app to my project, but after video is uploaded page shows error 
**Couldn't find Video without an ID**

After investigation i found that in the last url request video_id is missing. 

first
_http://uploads.gdata.youtube.com/action/FormDataUpload/AIwbFAOJNJlLxqfQEmP5kqEOAJIzWCDZ3-QpZaAxzW4CxGmU56duXQszcG5W1u2pJOSA0CnR8J6bsyjkAafzoukIbFYhMQTnyg?nexturl=http://localhost:3000/videos/new/save_video?locale=en&video_id=31_

second
_http://localhost:3000/videos/new/save_video?locale=en&status=200&id=PNmfHinnqW0_

there is no video_id. 

can you help me? thanks

**Comment by Elgeor** [comment]
realy nobody can help ?

**Comment by chebyte** [comment]
the problem is from you code, it is not a bug on the gem, when you upload some video it returns 

status=200&id=PNmfHinnqW0

but you can add params that you need that it returns please read the doc or see the code example

  @upload_info = YouTubeIt::Client.new.upload_token(params, url_to_redirect)

cheers!
